---
title: "Confidence"
author: "Filip Děchtěrenko"
date: "26 4 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
```

## read data

```{r}
df <- readRDS("rating_example.rds")
colnames(df) <- colnames(df) %>% str_replace("old.","old_") %>% str_replace("new.","new_")

df <- df %>% select(stimuli, time, everything())
m <- df %>% select_if(is.numeric) %>% as.matrix()


```

Relative cumsums

```{r}
m_p <- m %>% prop.table(margin = 1)
m_p %>% round(3)
m_cump <- t(apply(m_p, 1, cumsum))
m_cump <- m_cump[,-6]
d <- qnorm(m_cump)
d[1,]-d[2,]
d[3,]-d[4,]
```

and using dplyr

```{r}
df1 <- rbind(df %>% select(-starts_with("new")) %>% 
  pivot_longer(cols = old_Very.sure:old_Not.sure.at.all, values_to = "n") %>% 
  separate(name, into = c("response", "confidence"), sep = "_",remove = F),
df %>% select(-starts_with("old")) %>% 
  pivot_longer(cols = new_Very.sure:new_Not.sure.at.all, values_to = "n") %>% 
  separate(name, into = c("response", "confidence"), sep = "_",remove = F)) %>% 
  mutate(ord = factor(name, levels = c("old_Very.sure", "old_Somewhat.sure", "old_Not.sure.at.all", "new_Not.sure.at.all", "new_Somewhat.sure", "new_Very.sure"))) %>% select(-name)
df_SDT <- df1 %>% 
  arrange(stimuli, time,ord) %>% # arrange
  group_by(stimuli, time) %>% # for every group
  mutate(n_r = n/sum(n)) %>% # relative sums
  mutate(cum_nr = cumsum(n_r)) %>% # cum sum
  mutate(z = qnorm(cum_nr)) %>% # z-scores
  filter(!is.infinite(z))
df_SDT  

p1 <- df_SDT %>% 
  select(-n, -ord, -n_r, -z) %>% 
  pivot_wider(values_from = cum_nr, names_from = stimuli) %>% 
  ggplot(aes(x = New, y = Old, col = time)) + geom_point() + theme(aspect.ratio = 1) + 
  geom_path()

p2 <- df_SDT %>% 
  select(-n, -ord, -n_r, -cum_nr) %>% 
  pivot_wider(values_from = z, names_from = stimuli) %>% 
  mutate(d = Old- New) %>% 
  ggplot(aes(x = New, y = Old, col = time)) + geom_point() + theme(aspect.ratio = 1) + 
  geom_path()
```

```{r}
p1 + p2
```

```{r d_a}
# equal variance SDT
df_SDT_eq_var <- df1 %>% 
  group_by(stimuli, time,response) %>% 
  summarize(n = sum(n)) %>% 
  group_by(time) %>% 
  summarize(H = sum(n[response == "old"&stimuli == "Old"])/sum(n[stimuli=="Old"]),
            FA = sum(n[response == "old"&stimuli == "New"])/sum(n[stimuli=="Old"])) %>% 
  mutate(zH = qnorm(H),
         zFA = qnorm(FA),
         d= zH-zFA)

df3 <- df_SDT %>% 
  select(-n, -ord, -n_r, -cum_nr) %>% 
  pivot_wider(values_from = z, names_from = stimuli) 
df_s <- df3 %>% 
  group_by(time) %>% 
  do(x=lm(Old~New,.) %>% broom::tidy()) %>% 
  unnest(cols = x) %>% 
  filter(term == "New") %>% 
  select(time, s = estimate)
df_SDT_eq_var %>% 
  left_join(df_s, by = "time") %>% 
  mutate(d_a = sqrt(2/(1+s^2))*(zH-zFA))
```